--ЗАПОЛНЕНИЕ ДАННЫХ
--ДАННЫЕ MPA
INSERT INTO MPA (ID,NAME) VALUES (1,'G');
INSERT INTO MPA (ID,NAME) VALUES (2,'PG');
INSERT INTO MPA (ID,NAME) VALUES (3,'PG-13');
INSERT INTO MPA (ID,NAME) VALUES (4,'R');
INSERT INTO MPA (ID,NAME) VALUES (5,'NC-17');

--ДАННЫЕ ЖАНРА
INSERT INTO GENRES (ID,NAME) VALUES (1,'Комедия');
INSERT INTO GENRES (ID,NAME) VALUES (2,'Драма');
INSERT INTO GENRES (ID,NAME) VALUES (3,'Мультфильм');
INSERT INTO GENRES (ID,NAME) VALUES (4,'Триллер');
INSERT INTO GENRES (ID,NAME) VALUES (5,'Документальный');
INSERT INTO GENRES (ID,NAME) VALUES (6,'Боевик');