--MPA
CREATE TABLE IF NOT EXISTS MPA
(
    FILM_ID INTEGER AUTO_INCREMENT ,
    ID   INTEGER AUTO_INCREMENT
        UNIQUE ,
    NAME CHARACTER VARYING(64) NOT NULL ,
    CONSTRAINT MPA_PK
        PRIMARY KEY (ID)
);

--Фильмы
CREATE TABLE IF NOT EXISTS FILM
(
    ID      INTEGER AUTO_INCREMENT
        UNIQUE ,
    NAME    CHARACTER VARYING  NOT NULL,
    DESCRIPTION  CHARACTER VARYING NOT NULL,
    RELEASE_DATE DATE                   NOT NULL,
    DURATION     INTEGER                NOT NULL,
    MPA_ID       INTEGER                NOT NULL ,
    CONSTRAINT FILMS_PK
        PRIMARY KEY (ID),
    CONSTRAINT FILM_MPA_PK FOREIGN KEY (MPA_ID) REFERENCES MPA(ID)
);

--Жанры
CREATE TABLE IF NOT EXISTS GENRE
(
    ID   INTEGER AUTO_INCREMENT
        UNIQUE ,
    NAME CHARACTER VARYING(64) NOT NULL ,
    CONSTRAINT GENRE_PK
        PRIMARY KEY (ID)
);

--Пользователи
CREATE TABLE IF NOT EXISTS USER
(
    ID   INTEGER AUTO_INCREMENT
        UNIQUE ,
    EMAIL     CHARACTER VARYING NOT NULL ,
    LOGIN     CHARACTER VARYING NOT NULL
        UNIQUE ,
    NAME CHARACTER VARYING ,
    BIRTHDAY  DATE                  NOT NULL ,
    CONSTRAINT USER_ID_PK
        PRIMARY KEY (ID)
);

--Лайки
CREATE TABLE IF NOT EXISTS LIKES
(
    FILM_ID INTEGER AUTO_INCREMENT,
    USER_ID INTEGER AUTO_INCREMENT,
    CONSTRAINT LIKE_FILM_PK
        PRIMARY KEY (USER_ID),
    CONSTRAINT "LIKE_FILM_FILM_ID_FK"
        FOREIGN KEY (FILM_ID) REFERENCES FILM,
    CONSTRAINT "LIKE_FILM_USER_ID_FK"
        FOREIGN KEY (USER_ID) REFERENCES USER
);

--Жанр
CREATE TABLE IF NOT EXISTS GENRE_FILMS
(
    FILM_ID       INTEGER AUTO_INCREMENT,
    GENRE_ID      INTEGER NOT NULL ,
    ID_GENRE_FILM INTEGER AUTO_INCREMENT
        UNIQUE ,
    CONSTRAINT GENRE_FILM_PK
        PRIMARY KEY (ID_GENRE_FILM),
    CONSTRAINT "GENRE_FILM_FILMS_PK"
        FOREIGN KEY (FILM_ID) REFERENCES FILM (ID),
    CONSTRAINT "GENRE_FILM_GENRE_PK"
        FOREIGN KEY (GENRE_ID) REFERENCES GENRE (ID)
);
--Друзья пользователя
CREATE TABLE IF NOT EXISTS USER_FRIENDS
(
    ID   INTEGER AUTO_INCREMENT
        UNIQUE ,
    USER_ID          INTEGER NOT NULL ,
    FRIENDS_ID        INTEGER NOT NULL,
    CONSTRAINT USER_FRIENDS_PK
        PRIMARY KEY (ID),
    CONSTRAINT "USER_FRIENDS_USER_FK"
        FOREIGN KEY (USER_ID) REFERENCES USER,
    CONSTRAINT "USER_FRIENDS_FRIEND_FK"
        FOREIGN KEY (FRIENDS_ID) REFERENCES USER
);

--MPA фильма
CREATE TABLE IF NOT EXISTS MPA_FILM
(
    FILM_ID INTEGER not null,
    MPA_ID  INTEGER auto_increment,
    constraint MPA_FILM_PK
        primary key (FILM_ID),
    constraint "mpa_film_MPA_fk"
        foreign key (MPA_ID) references MPA (ID)
);